CREATE TABLE IF NOT EXISTS `User`(
userName VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
firstName VARCHAR(100) NOT NULL,
lastName VARCHAR(100) NOT NULL,
PRIMARY KEY(email)
) ENGINE = INNODB;